server:
  error:
    include-message: always
spring:
  security:
    user:
      name: abn
      password: 1234
  datasource:
    url: jdbc:postgresql://db:5432/recipedb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false

non-vegetarian: ANIMAL_PROTEIN,FISH

